apiVersion: v1
kind: Secret
metadata:
  name: mt-secrets
type: Opaque   #Tipo padr√£o (chave-valor simples)
stringData:
  POSTGRES_USER: "usuario_banco"
  POSTGRES_DB: "nome_banco"
  POSTGRES_PASSWORD: "senha_banco"
  APP_SECRET_KEY: "secret_key"
  DJANGO_SUPERUSER_PASSWORD: "senha_superuser"
  EMAIL_HOST_PASSWORD: "senha_email"
  REPLICATION_USER: "usuario_replicacao"
  REPLICATION_PASSWORD: "senha_replicacao"