apiVersion: v1
kind: ConfigMap
metadata:
  name: mt-worker-configmap
data:
  PORT: "5000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-worker-deployment
  labels:
    app: mt-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mt-worker
  template:
    metadata:
      labels:
        app: mt-worker
    spec:
      containers:
        - name: mt-worker-container
          #image: gcr.io/tcc-mt/machine-teaching-worker:latest
          image: nickashu/worker_teste:v1.0
          imagePullPolicy: Always
          #resources:
          #  requests:
          #    memory: "512Mi"
          #    cpu: "500m"
          #  limits:
          #    memory: "1Gi"
          #    cpu: "1"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mt-worker-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: mt-worker-svc
spec:
  selector:
    app: mt-worker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
